apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: domain-multi-com-tls
spec:
  secretName: domain-multi-com
  issuerRef:
    name: letsencrypt-prod 
    kind: ClusterIssuer
  commonName: domain-multi.com
  dnsNames:
    - domain-multi.com
    - www.domain-multi.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains: 
          - domain-multi.com
          - www.domain-multi.com